name: rutracker_app
description: Приложение для прослушивания аудиокниг.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.2.1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  path_provider: ^2.0.8
  html: ^0.15.0
  flutter_downloader: ^1.7.1
  torrent_task: ^0.3.0
  floating_bottom_navigation_bar: ^1.5.2
  percent_indicator: ^3.4.0
  shimmer: ^2.0.0
  dartorrent_common: ^1.0.3
  sqflite: ^2.0.1
  shared_preferences: ^2.0.11
  audiotagger: ^2.2.1
  easy_dynamic_theme: ^2.2.0
  just_audio: ^0.9.20
  cached_network_image: ^3.2.0
  audio_service: ^0.18.4
  just_audio_background: ^0.0.1-beta.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/GothamPro-Light.ttf
